import React from "react";
import Link from "next/link";
import {
  Brain,
  Zap,
  Code2,
  Users,
  BarChart3,
} from "lucide-react";

const features = [
  {
    icon: Brain,
    title: "AI-Powered Questions",
    description:
      "Interview questions dynamically generated by advanced AI based on your job role, experience level, and industry.",
    color: "from-indigo-500 to-indigo-600",
    bgColor: "bg-indigo-50",
    iconColor: "text-indigo-600",
    link: "/dashboard/questions",
  },
  {
    icon: Zap,
    title: "Real-Time Feedback",
    description:
      "Receive instant, detailed feedback on your answers after each question — including strengths and areas to improve.",
    color: "from-purple-500 to-purple-600",
    bgColor: "bg-purple-50",
    iconColor: "text-purple-600",
    link: "/dashboard/feedback",
  },
  {
    icon: Code2,
    title: "Technical Interview",
    description:
      "Practice coding challenges, system design, and technical concepts with AI-driven technical interview sessions.",
    color: "from-cyan-500 to-cyan-600",
    bgColor: "bg-cyan-50",
    iconColor: "text-cyan-600",
    link: "/dashboard/technical",
  },
  {
    icon: Users,
    title: "HR Interview",
    description:
      "Prepare for behavioral and HR interviews with questions about leadership, teamwork, and workplace scenarios.",
    color: "from-orange-500 to-orange-600",
    bgColor: "bg-orange-50",
    iconColor: "text-orange-600",
    link: "/dashboard/hr",
  },
  {
    icon: BarChart3,
    title: "Performance Reports",
    description:
      "Get comprehensive performance reports with ratings, detailed analysis, and actionable improvement tips.",
    color: "from-emerald-500 to-emerald-600",
    bgColor: "bg-emerald-50",
    iconColor: "text-emerald-600",
    link: "/dashboard/performance",
  },
];

const Features = () => {
  return (
    <section id="features" className="py-20 sm:py-28 bg-gray-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <span className="inline-block text-sm font-semibold text-indigo-600 bg-indigo-50 px-4 py-1.5 rounded-full mb-4">
            Features
          </span>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-gray-900">
            Everything you need to{" "}
            <span className="gradient-text">ace your interview</span>
          </h2>
          <p className="mt-5 text-lg text-gray-600">
            Our platform combines cutting-edge AI with proven interview
            strategies to give you the ultimate preparation experience.
          </p>
        </div>

        {/* Feature Cards */}
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature, index) => {
            const Icon = feature.icon;
            return (
              <Link
                key={feature.title}
                href={feature.link}
                className="group relative bg-white rounded-3xl p-7 shadow-sm border border-gray-100 card-hover block"
              >
                <div
                  className={`w-14 h-14 rounded-2xl ${feature.bgColor} flex items-center justify-center mb-5 group-hover:scale-110 transition-transform duration-300`}
                >
                  <Icon className={`w-7 h-7 ${feature.iconColor}`} />
                </div>
                <h3 className="text-xl font-bold text-gray-900 mb-3">
                  {feature.title}
                </h3>
                <p className="text-gray-500 leading-relaxed">
                  {feature.description}
                </p>
                <div
                  className={`absolute bottom-0 left-0 right-0 h-1 rounded-b-3xl bg-gradient-to-r ${feature.color} opacity-0 group-hover:opacity-100 transition-opacity duration-300`}
                />
              </Link>
            );
          })}
        </div>
      </div>
    </section>
  );
};

export default Features;
