const { seedCourse } = require('./seed-helpers');

const Q = [
  ["ER Model", "Easy", "In an ER diagram, which symbol represents an entity set?", ["Rectangle", "Diamond", "Ellipse", "Double line"], "A", "Entity sets are drawn as rectangles; diamonds denote relationship sets and ellipses denote attributes."],
  ["ER Model", "Easy", "A diamond symbol in an ER diagram denotes:", ["A key attribute", "A derived attribute", "A relationship set", "A weak entity"], "C", "Diamonds connect entity sets and represent relationship sets between them."],
  ["ER Model", "Easy", "Which of the following best describes an entity in the ER model?", ["A saved query result", "A real-world object or concept, distinguishable from others, about which data is stored", "A constraint between two tables", "An index structure"], "B", "An entity is a distinguishable real-world object or concept, such as a person, place, or course."],

  ["ER Model", "Medium", "A weak entity set is one that:", ["Contains no descriptive attributes", "Cannot be identified by its own attributes alone and depends on an identifying (owner) entity", "Has more than one primary key", "Participates in no relationships"], "B", "Its instances are identified by combining the owner entity's primary key with the weak entity's own partial (discriminator) key."],
  ["ER Model", "Medium", "Total participation of an entity set E in a relationship R means:", ["Every instance of E must appear in at least one instance of R, shown by a double line", "Only the key attributes of E participate", "Participation of E is optional", "Each instance of E participates at most once"], "A", "Total participation means every entity instance takes part in the relationship, depicted with double lines in the ER diagram."],
  ["ER Model", "Medium", "A double ellipse in an ER diagram represents:", ["A derived attribute", "A key attribute", "A multivalued attribute", "A composite attribute"], "C", "Double ovals mark multivalued attributes such as multiple phone numbers for one person."],
  ["ER Model", "Medium", "Aggregation in the ER model is used when:", ["Two entity sets share identical attributes", "A relationship set has no attributes of its own", "An entity relates only to itself", "A relationship, together with its participating entity sets, must itself participate in another relationship"], "D", "Aggregation abstracts a relationship and its entities into a single higher-level entity so it can take part in further relationships."],

  ["ER Model", "Hard", "When mapping a weak entity set W with partial key wnum, owned by strong entity E with key eid, to relational tables, the primary key of W's relation is:", ["wnum alone", "eid alone", "eid combined with wnum", "A newly invented surrogate key is mandatory"], "C", "The weak entity's relation carries the owner's key as a foreign key, and the composite (eid, wnum) serves as its primary key."],
  ["ER Model", "Hard", "In a specialization hierarchy marked with the disjoint (d) constraint:", ["An entity must belong to every subclass", "An entity may belong to at most one subclass", "All subclasses must have identical attributes", "Membership in a subclass is mandatory"], "B", "The disjoint constraint forbids an entity from simultaneously belonging to two or more lower-level subclasses."],
  ["ER Model", "Hard", "Which statement about converting a ternary relationship among entity sets A, B, and C into the relational model is correct?", ["It can always be replaced by three binary relationships without information loss", "It generally requires its own relation holding foreign keys to A, B, and C, because decomposition into binaries can lose information", "It mandates merging the tables of A, B, and C into one table", "It cannot be represented in the relational model"], "B", "A ternary relationship typically becomes its own table referencing the three entity keys; splitting it into pairwise binaries may lose which triple combinations actually occurred."],

  ["Normalization", "Easy", "The primary goal of normalization is to:", ["Encrypt sensitive columns", "Reduce redundancy and avoid insertion, deletion, and update anomalies", "Make every SELECT query run faster", "Compress storage on disk"], "B", "Normal forms organize relations so facts are stored once, eliminating anomalies caused by duplicated data."],
  ["Normalization", "Easy", "A relation is in First Normal Form (1NF) when:", ["It contains repeating groups within cells", "Attributes may hold comma-separated lists", "Every row-column cell holds exactly one atomic value", "Duplicate rows are allowed"], "C", "1NF requires atomic attribute values, banning repeating groups and nested structures inside cells."],
  ["Normalization", "Easy", "Second Normal Form (2NF) eliminates:", ["Transitive dependencies", "Partial dependencies of non-prime attributes on part of a candidate key", "Multivalued dependencies", "Join dependencies"], "B", "2NF demands that non-prime attributes depend on the whole candidate key, removing partial dependencies."],

  ["Normalization", "Medium", "A transitive dependency exists when:", ["X determines Y directly", "Some Z exists with X -> Z and Z -> Y while X is not a superkey", "Y depends on no attribute", "Two attributes determine each other simultaneously"], "B", "This indirect chain X -> Z -> Y is what Third Normal Form (3NF) is designed to eliminate for non-key attributes."],
  ["Normalization", "Medium", "Consider R(A, B, C) with functional dependencies AB -> C and C -> B. The highest normal form of R is:", ["1NF", "2NF", "3NF", "BCNF"], "C", "Candidate keys are AB and AC, so every attribute is prime; C -> B is acceptable in 3NF because B is prime, but violates BCNF since C is not a superkey."],
  ["Normalization", "Medium", "Decomposing relation R into R1 and R2 is lossless-join if and only if:", ["(R1 intersect R2) -> (R1 - R2) or (R1 intersect R2) -> (R2 - R1)", "(R1 union R2) -> (R1 intersect R2)", "Both relations contain the same number of tuples", "The shared attribute is numeric"], "A", "If the common attributes functionally determine all attributes of at least one side, joining R1 and R2 reproduces exactly the original relation."],
  ["Normalization", "Medium", "A relation is in Boyce-Codd Normal Form (BCNF) if, for every non-trivial functional dependency X -> Y:", ["Y is a prime attribute", "X is a superkey", "Y is a superkey", "X contains at least two attributes"], "B", "BCNF strengthens 3NF by demanding that every determinant of a non-trivial FD be a superkey."],

  ["Normalization", "Hard", "Which statement comparing BCNF and 3NF decompositions is TRUE?", ["Every 3NF relation is also in BCNF", "Every BCNF relation is in 3NF, yet a lossless, dependency-preserving BCNF decomposition may not exist, while 3NF synthesis always achieves both", "BCNF decompositions always preserve dependencies", "3NF permits strictly more redundancy than 2NF"], "B", "BCNF implies 3NF, but enforcing BCNF can force dropping dependency preservation; the 3NF synthesis algorithm guarantees losslessness and dependency preservation together."],
  ["Normalization", "Hard", "Relation R(A, B, C) has non-trivial multivalued dependencies A ->> B and A ->> C. R is in Fourth Normal Form (4NF) only if:", ["B and C are prime attributes", "A ->> C is redundant", "R has a single-attribute key", "A is a superkey of R"], "D", "4NF requires every non-trivial MVD's determinant to be a superkey, preventing unrelated facts about A from being stored independently."],
  ["Normalization", "Hard", "A relation containing a non-trivial join dependency that cannot be inferred from its candidate keys must be decomposed further to satisfy:", ["2NF", "3NF", "5NF (Project-Join Normal Form)", "1NF"], "C", "Fifth Normal Form deals with join dependencies, ensuring every decomposition can be rejoined losslessly without spurious information."],

  ["SQL Commands", "Easy", "Which command removes ALL rows from a table quickly while keeping the table structure?", ["DELETE", "TRUNCATE", "DROP", "REVOKE"], "B", "TRUNCATE deallocates all rows while retaining the schema; DROP removes the table entirely."],
  ["SQL Commands", "Easy", "CREATE, ALTER, and DROP belong to which category of SQL commands?", ["DDL (Data Definition Language)", "DML (Data Manipulation Language)", "DCL (Data Control Language)", "TCL (Transaction Control Language)"], "A", "These commands define or change schema objects, placing them in DDL."],
  ["SQL Commands", "Easy", "Which clause filters aggregated groups produced by GROUP BY?", ["WHERE", "ORDER BY", "HAVING", "DISTINCT"], "C", "WHERE filters individual rows before grouping; HAVING filters groups afterward."],

  ["SQL Commands", "Medium", "Inside a transaction in Oracle, which statement about rollback is correct?", ["Neither DELETE nor TRUNCATE can be rolled back", "DELETE can be rolled back, whereas TRUNCATE is a DDL operation that cannot", "TRUNCATE can be rolled back but DELETE never can", "Both always commit immediately upon execution"], "B", "DELETE is logged DML and reversible until commit; Oracle's TRUNCATE implicitly commits and cannot be undone."],
  ["SQL Commands", "Medium", "A table has 10 rows and column phone is NULL in 3 of them. What does SELECT COUNT(phone) return?", ["10", "3", "0", "7"], "D", "Aggregate functions ignore NULLs, so COUNT(phone) counts only the 7 non-NULL values; COUNT(*) would return 10."],
  ["SQL Commands", "Medium", "Which correctly distinguishes UNION from UNION ALL?", ["UNION ALL removes duplicates", "UNION eliminates duplicate rows while UNION ALL keeps all rows, making UNION ALL cheaper", "They are interchangeable with identical performance", "UNION combines tables column-wise"], "B", "UNION performs duplicate elimination (usually via sort or hashing), so UNION ALL is faster when duplicates are acceptable."],
  ["SQL Commands", "Medium", "In standard SQL, every non-aggregated column in the SELECT list of a grouped query must:", ["Appear in the GROUP BY clause", "Be numeric", "Have an index", "Be declared UNIQUE"], "A", "Otherwise the value per group would be ambiguous, so the standard requires grouped or aggregated expressions only."],

  ["SQL Commands", "Hard", "What does SELECT * FROM t WHERE col = NULL return?", ["Rows where col is NULL", "No rows, because comparing with NULL yields UNKNOWN; IS NULL must be used instead", "All rows in the table", "A syntax error in standard SQL"], "B", "Any comparison with NULL evaluates to UNKNOWN, and WHERE keeps only TRUE rows, so equality with NULL never matches."],
  ["SQL Commands", "Hard", "With ties on the ORDER BY key, which ranking functions assign the SAME value to tied rows?", ["ROW_NUMBER and RANK", "NTILE and ROW_NUMBER", "RANK and DENSE_RANK", "Only LAG"], "C", "ROW_NUMBER breaks ties arbitrarily; RANK gives ties equal ranks with gaps, and DENSE_RANK gives equal ranks without gaps."],
  ["SQL Commands", "Hard", "The MERGE statement (often called UPSERT) performs which operation?", ["Permanently fuses two tables into one schema", "Creates indexes on both source and target tables", "Deletes duplicate rows across tables", "Conditionally INSERTs, UPDATEs, or DELETEs target rows based on matching rows from a source, all in one statement"], "D", "MERGE joins source to target and applies conditional insert/update/delete actions per match, implementing upsert logic atomically."],

  ["Transactions and ACID", "Easy", "The ACID property stating that a transaction executes either completely or not at all is:", ["Atomicity", "Consistency", "Isolation", "Durability"], "A", "Atomicity guarantees all-or-nothing execution, typically enforced via logging and rollback."],
  ["Transactions and ACID", "Easy", "After COMMIT returns successfully, the changes survive a subsequent system crash. This property is:", ["Isolation", "Atomicity", "Durability", "Consistency"], "C", "Durability ensures committed updates are persisted to stable storage and are never lost."],
  ["Transactions and ACID", "Easy", "The consistency property of ACID states that a transaction:", ["Runs concurrently with others", "Moves the database from one valid state to another, preserving all integrity constraints", "Never reads data from disk", "Commits instantaneously"], "B", "Consistency requires that the database obey all rules and constraints before and after the transaction."],

  ["Transactions and ACID", "Medium", "Transaction T1 reads a value modified by T2 before T2 commits. This is called a:", ["Phantom read", "Non-repeatable read", "Lost update", "Dirty read"], "D", "Reading uncommitted (possibly aborted) data of another transaction is a dirty read."],
  ["Transactions and ACID", "Medium", "Basic two-phase locking (2PL) guarantees which property of concurrent schedules?", ["Freedom from deadlock", "Conflict-serializability", "That no transaction ever blocks another", "Snapshot isolation"], "B", "Growing then shrinking lock phases ensure every 2PL schedule is conflict-serializable, though deadlocks remain possible."],
  ["Transactions and ACID", "Medium", "The weakest standard SQL isolation level that prevents dirty reads is:", ["READ UNCOMMITTED", "SERIALIZABLE", "READ COMMITTED", "None of the levels prevent dirty reads"], "C", "READ COMMITTED allows non-repeatable reads and phantoms but only permits reading committed data."],
  ["Transactions and ACID", "Medium", "Under the wait-die deadlock prevention scheme, when a YOUNGER transaction requests a lock held by an OLDER transaction:", ["The older transaction aborts", "The younger transaction aborts (dies) and restarts later with its original timestamp", "Both transactions abort", "The lock is transferred immediately"], "B", "Wait-die lets older transactions wait for younger ones but forces younger requesters to die and retry."],

  ["Transactions and ACID", "Hard", "T1 runs a predicate query twice and, in between, T2 inserts new rows matching that predicate, which T1 then sees. This anomaly is a:", ["Dirty read", "Phantom read", "Lost update", "Deadlock"], "B", "Newly matching rows are phantoms; preventing them requires SERIALIZABLE isolation (or predicate locking)."],
  ["Transactions and ACID", "Hard", "The Thomas Write Rule increases concurrency by:", ["Aborting every writer involved in a conflict", "Ignoring an outdated overwrite from an earlier-timestamped transaction, yielding a view-serializable schedule even when it is not conflict-serializable", "Locking entire tables during writes", "Randomly delaying commit processing"], "B", "Discarding the obsolete write preserves view equivalence to the serial order, allowing schedules that conflict-serializability would reject."],
  ["Transactions and ACID", "Hard", "Under snapshot isolation, two transactions each read overlapping data, write disjoint rows, and together violate a business constraint. This anomaly is known as:", ["Dirty read", "Phantom read", "Write skew", "Cascading abort"], "C", "Snapshot isolation detects only write-write conflicts on the same rows, so disjoint writes that jointly break an invariant slip through as write skew."],

  ["Indexing", "Easy", "The main purpose of a database index is to:", ["Reduce the size of the base table", "Enforce column encryption", "Speed up data retrieval at the cost of extra storage and slower writes", "Compress transaction logs"], "C", "Indexes provide fast access paths but add space overhead and maintenance cost on inserts, updates, and deletes."],
  ["Indexing", "Easy", "Leaf nodes of a B+ tree index are linked together, which makes which operation efficient?", ["Point inserts only", "Range queries and ordered scans", "Automatic encryption", "Lossless compression"], "B", "Following the linked-leaf list visits keys in sorted order, ideal for range predicates and ORDER BY."],
  ["Indexing", "Easy", "A clustered index is one that:", ["Dictates the physical order of rows, so a table can have only one", "Can be created many times per table", "Stores rows in random heap order", "Is required by every foreign key"], "A", "Because data rows themselves are stored in key order, at most one clustered index can exist per table."],

  ["Indexing", "Medium", "A sparse index, which stores one entry per block rather than per record, is feasible only when:", ["The file uses hash bucket layout", "All records are fixed-length", "The index is a secondary index", "The file is physically sorted on the indexed (clustering) key"], "D", "Sparse indexing relies on the file's physical order matching the index key so each entry locates a whole block."],
  ["Indexing", "Medium", "Secondary (non-clustering) indexes must typically be dense because:", ["They store entire rows", "Record order does not follow the index key, so an entry is needed for every key value", "They occupy less space than sparse ones", "Database administrators mandate it"], "B", "Since the file is not ordered on the secondary key, a sparse index could not locate records reliably."],
  ["Indexing", "Medium", "Given composite index (city, age), which queries use it efficiently?", ["Any combination of attributes equally", "Filters on age alone, as effectively as city", "Filters on city alone, or on city and age (the leftmost-prefix rule), but not efficiently on age alone", "None, composite indexes only help ORDER BY"], "C", "Entries are sorted first by city then age, so the index is usable only when the leading column(s) are constrained."],
  ["Indexing", "Medium", "Hash-based indexes are well suited for:", ["Range scans between two keys", "Serving ORDER BY clauses", "Equality lookups, while remaining poor for range predicates", "Full-text search"], "C", "Hashing destroys key ordering, so it answers point queries quickly but cannot support ranges or sorting."],

  ["Indexing", "Hard", "A B+ tree has fan-out 100 and indexes 1,000,000 keys. Approximately how many node accesses are needed from root to leaf?", ["About 3", "About 6", "About 10", "About 20"], "A", "Height is roughly log base 100 of 1,000,000 = 3, illustrating why tall, thin B+ trees need few disk reads."],
  ["Indexing", "Hard", "A covering index improves performance when:", ["It covers all disk platters", "Table rows exceed page size", "The query involves joins only", "Every column the query needs resides in the index, letting the engine answer from the index alone without touching the table"], "D", "Index-only scans avoid costly table lookups, which is why INCLUDE columns are added to create covering indexes."],
  ["Indexing", "Hard", "Bitmap indexes are most appropriate for:", ["High-cardinality columns in hot OLTP tables", "Low-cardinality columns in read-mostly analytical workloads, where bitmaps combine efficiently via AND/OR", "Write-heavy message queues", "Storing binary large objects"], "B", "Bitmaps shine when few distinct values are combined across dimensions in read-intensive queries, but concurrent updates fragment them badly."],

  ["Constraints", "Easy", "A PRIMARY KEY constraint enforces:", ["That NULL values are allowed", "Uniqueness and NOT NULL, with at most one primary key per table", "Column-level encryption", "Physical sort order of rows"], "B", "The key uniquely identifies each row and no component may be NULL."],
  ["Constraints", "Easy", "A FOREIGN KEY constraint primarily maintains:", ["Row compression", "Column default values", "Index clustering", "Referential integrity between related tables"], "D", "It ensures values in the referencing column correspond to existing rows in the referenced table."],
  ["Constraints", "Easy", "Which statement about UNIQUE constraints is TRUE in most SQL systems?", ["Multiple UNIQUE constraints are allowed per table and they accept NULL values, unlike the single NOT NULL primary key", "UNIQUE columns reject NULL values in all systems", "A table may declare several primary keys", "UNIQUE always creates a clustered index"], "A", "UNIQUE permits NULLs and can be applied to several columns, whereas a table has exactly one primary key."],

  ["Constraints", "Medium", "Declaring a foreign key with ON DELETE CASCADE means that deleting a parent row:", ["Is blocked while children exist", "Sets the children's foreign key columns to NULL", "Automatically deletes all matching child rows", "Renames the child table"], "C", "Cascade propagates the delete to dependent rows, keeping the relationship consistent."],
  ["Constraints", "Medium", "A CHECK constraint such as CHECK (salary >= 0) ensures that:", ["The salary column is indexed", "Every inserted or updated row satisfies the predicate, and violating changes are rejected", "Salary values are encrypted", "Other columns inherit the same rule"], "B", "CHECK validates each row against a boolean expression, enforcing domain restrictions."],
  ["Constraints", "Medium", "The DEFAULT column constraint specifies:", ["A maximum allowed value", "A value assigned automatically when the column is omitted from an INSERT", "Auto-increment behavior", "A fallback used when a query fails"], "B", "Omitted inserts receive the predefined default rather than NULL."],
  ["Constraints", "Medium", "Deferrable constraints declared INITIALLY DEFERRED are especially useful when:", ["Rebuilding indexes online", "Loading data very slowly", "Renaming columns", "Circular or mutually referencing foreign keys must temporarily be violated during a transaction"], "D", "Checking at commit lets each row of a circular dependency be inserted before validation occurs."],

  ["Constraints", "Hard", "How does CREATE ASSERTION differ from a table-level CHECK constraint?", ["Assertions define constraints spanning multiple tables, while a CHECK applies only to its own table", "Assertions execute faster than CHECK", "Assertions apply exclusively to views", "There is no semantic difference"], "A", "Assertions are schema-level predicates, e.g., relating totals across two tables, which single-table CHECK cannot express."],
  ["Constraints", "Hard", "Which statement contrasts RESTRICT with NO ACTION for foreign keys?", ["They are exact synonyms in every case", "NO ACTION blocks immediately while RESTRICT defers", "RESTRICT rejects the delete attempt immediately, whereas NO ACTION behaves similarly but its check may be deferred to the end of the statement or transaction where deferral is supported", "Both automatically cascade deletions"], "C", "Both forbid orphaning children, but only NO ACTION can be postponed under deferrable constraint checking."],
  ["Constraints", "Hard", "A two-column foreign key declared MATCH FULL requires that:", ["Either component may be NULL independently", "Either both components are NULL or both are non-NULL and valid; MATCH SIMPLE, by contrast, passes the check whenever any component is NULL", "The key has a single column", "Values are hashed before comparison"], "B", "MATCH FULL forbids partially NULL composite keys, closing loopholes that MATCH SIMPLE permits."],

  ["Joins and Subqueries", "Easy", "An INNER JOIN returns:", ["Only rows having matches in both joined tables", "All rows of the left table", "The Cartesian product of both tables", "Unmatched rows from the right table only"], "A", "Non-matching rows from either side are discarded in an inner join."],
  ["Joins and Subqueries", "Easy", "A LEFT OUTER JOIN produces:", ["Matching rows only", "Every row of the left table, with NULLs filling right-side columns where no match exists", "Only rows of the right table", "The symmetric difference of the tables"], "B", "Left outer joins preserve all left rows, padding unmatched right attributes with NULL."],
  ["Joins and Subqueries", "Easy", "A CROSS JOIN between a table with m rows and one with n rows yields:", ["m + n rows", "min(m, n) rows", "m * n rows", "m - n rows"], "C", "Without a join condition, every left row pairs with every right row."],

  ["Joins and Subqueries", "Medium", "A FULL OUTER JOIN returns:", ["Inner-matching rows only", "Left-table rows only", "Right-table rows only", "Matched rows plus unmatched rows from BOTH sides, padded with NULLs"], "D", "It combines the effect of left and right outer joins, preserving unmatched rows of both inputs."],
  ["Joins and Subqueries", "Medium", "A NATURAL JOIN differs from a regular join because it:", ["Equates all identically named column pairs automatically and outputs them once", "Requires an explicit USING clause", "Produces a union of rows", "Ignores column names entirely"], "A", "Natural join implicitly matches every shared column name, avoiding duplication of the join columns."],
  ["Joins and Subqueries", "Medium", "A correlated subquery is one that:", ["Executes once, independent of the outer query", "References columns of the outer query and is logically evaluated once per candidate outer row", "Cannot use indexes", "Must always return a single scalar value"], "B", "Its dependence on outer-row values is why it re-evaluates per row unless the optimizer rewrites it."],
  ["Joins and Subqueries", "Medium", "To list each employee alongside their manager's name from a single table Emp(emp_id, name, mgr_id), you use a:", ["FULL OUTER JOIN to another table", "NATURAL JOIN", "Self join, aliasing Emp twice and matching employee mgr_id to the manager's emp_id", "CROSS JOIN"], "C", "A self join compares rows of the same relation under two aliases."],

  ["Joins and Subqueries", "Hard", "If the subquery inside NOT IN returns even one NULL, the outer NOT IN query:", ["Excludes only the offending rows", "Returns no rows at all, because every comparison with NULL yields UNKNOWN", "Raises an immediate error", "Treats NULL as the value zero"], "B", "x NOT IN (1, NULL) can never be TRUE, silently producing an empty result, a notorious SQL trap."],
  ["Joins and Subqueries", "Hard", "Which technique finds customers who have placed NO orders?", ["INNER JOIN followed by a filter", "RIGHT JOIN to Customers", "LEFT JOIN to Orders and retain rows where Orders.order_id IS NULL (anti-join)", "CROSS JOIN with duplicate elimination"], "C", "The preserved left rows lacking a match carry NULLs on the right side, isolating non-ordering customers."],
  ["Joins and Subqueries", "Hard", "The LATERAL keyword (as in PostgreSQL) allows a FROM-clause subquery to:", ["Reference columns of FROM items appearing earlier, enabling per-row subqueries that act like a join", "Only perform aggregations", "Execute solely against views", "Replace GROUP BY entirely"], "A", "Lateral references make the subquery re-evaluable per outer row while retaining join syntax and optimizer flexibility."],

  ["Views and Triggers", "Easy", "A database view is:", ["A physical copy of table data", "A scheduled backup job", "A virtual table whose defining query executes (or expands) at access time, while data remains in base tables", "A special kind of index"], "C", "Views store the definition, not the data, providing logical abstraction and security."],
  ["Views and Triggers", "Easy", "A trigger is:", ["A stored program that executes automatically in response to events such as INSERT, UPDATE, or DELETE", "A procedure invoked manually by users", "A nightly scheduled batch job", "A declarative constraint"], "A", "Triggers fire implicitly when their triggering event occurs on the associated table."],
  ["Views and Triggers", "Easy", "Unlike ordinary views, a materialized view:", ["Is purely virtual", "Physically stores its query results and must be refreshed to reflect changes in base tables", "Cannot have indexes built on it", "Always reflects base tables instantly with no cost"], "B", "Materialization trades storage and refresh cost for fast repeated query access."],

  ["Views and Triggers", "Medium", "In the simplest case, a view is updatable only when it is defined over:", ["A GROUP BY expression", "DISTINCT rows of several tables", "Aggregated columns", "A single base table and includes that table's key, with no aggregates, DISTINCT, or GROUP BY"], "D", "Each view row must map unambiguously to exactly one base-table row for direct DML."],
  ["Views and Triggers", "Medium", "A BEFORE row-level trigger differs from an AFTER trigger in that it:", ["Logs changes after commit", "Fires before the row is written and can modify or reject the change; AFTER fires once the write has occurred", "Fires in response to SELECT statements", "Replaces all declarative constraints"], "B", "BEFORE triggers commonly validate or transform values, while AFTER triggers handle follow-up actions like audit logging."],
  ["Views and Triggers", "Medium", "Creating a view WITH CHECK OPTION causes:", ["Updates or inserts through the view that would produce rows invisible to the view to be rejected", "The view to become materialized", "Privileges to propagate automatically", "Child rows to be deleted in cascade"], "A", "It prevents writing rows through the view that the view itself could not subsequently display."],
  ["Views and Triggers", "Medium", "Inside a row-level trigger, the :NEW and :OLD correlation names refer to:", ["Two concurrent sessions", "Backup copies of the whole table", "The new and pre-change versions of the current row (NEW for INSERT/UPDATE, OLD for UPDATE/DELETE)", "Temporary tables created by the trigger"], "C", "They expose the affected row's values before and after modification for use in trigger logic."],

  ["Views and Triggers", "Hard", "If an UPDATE affects 50 rows, a STATEMENT-level trigger fires how many times?", ["50 times, once per row", "Once for the triggering statement, regardless of how many rows were affected", "Exactly twice", "Not at all when rows are affected"], "B", "Statement-level triggers fire once per DML statement; row-level (FOR EACH ROW) triggers fire once per affected row."],
  ["Views and Triggers", "Hard", "INSTEAD OF triggers are significant because they:", ["Run before declarative constraints are checked", "Apply only to base tables", "Duplicate AFTER-trigger functionality", "Are defined on views and replace the attempted DML, making otherwise non-updatable views writable"], "D", "The database executes the trigger body instead of the original operation, translating it manually into base-table changes."],
  ["Views and Triggers", "Hard", "Performing an incremental (fast) refresh of a materialized view requires:", ["Nothing beyond the view itself", "Full exclusive locks on base tables", "Change-tracking logs (materialized view logs) on the base tables so only deltas are applied; absent these, a costly complete rebuild is needed", "Dropping all indexes on the view"], "C", "Fast refresh replays recorded base-table changes rather than recomputing the entire result set."],

  ["Query Optimization", "Easy", "The query optimizer's core task is to:", ["Parse SQL syntax", "Select the execution plan with the lowest estimated cost among equivalent plans producing the same result", "Store data pages to disk", "Validate foreign key constraints"], "B", "Many algebraically equivalent plans exist; the optimizer estimates costs and picks the cheapest."],
  ["Query Optimization", "Easy", "Which command displays the execution plan chosen for a query?", ["EXPLAIN", "COMMIT", "VACUUM", "GRANT"], "A", "EXPLAIN reveals operators, join methods, and estimated row counts without executing the query."],
  ["Query Optimization", "Easy", "A highly selective predicate (matching few rows) makes an index scan:", ["Irrelevant to planning", "Slower than sorting", "Impossible to use", "Preferable to a full table scan"], "D", "Touching few rows via an index beats reading every page, so planners favor indexes for selective filters."],

  ["Query Optimization", "Medium", "The classic heuristic in algebraic optimization is to:", ["Join tables first, filter later", "Materialize every intermediate result", "Push selections and projections down the tree early to shrink intermediate sizes", "Avoid indexes at all costs"], "C", "Reducing tuples and columns as early as possible lowers the input size of subsequent expensive operators."],
  ["Query Optimization", "Medium", "Cost-based optimizers choose plans using:", ["Random guessing among plans", "Catalog statistics such as relation sizes, distinct-value counts, histograms, and index metadata", "User-specified hints only", "Fixed constants independent of data"], "B", "Accurate statistics drive cardinality estimates, which in turn drive cost estimates."],
  ["Query Optimization", "Medium", "Pipelined execution benefits plans because it:", ["Passes tuples between operators in memory without writing intermediate results to disk", "Writes each operator's output to temporary tables", "Forces nested-loop joins", "Serializes concurrent queries"], "A", "Avoiding materialization saves I/O and lets consumers start receiving tuples before producers finish."],
  ["Query Optimization", "Medium", "Optimizers often restrict search to left-deep join trees because:", ["Mathematically only left-deep trees are valid", "Right-deep trees are syntactically illegal", "They minimize CPU register pressure only", "The left (outer) input streams once while the inner is reused repeatedly, bounding memory and enabling pipelined joins"], "D", "Limiting shape prunes the huge search space while preserving plans that pipeline efficiently."],

  ["Query Optimization", "Hard", "The System R style optimizer enumerates join orders using:", ["Exhaustive permutation of all orders regardless of cost", "Purely greedy extension", "Dynamic programming over subsets of relations, building optimal plans bottom-up and pruning dominated candidates", "Uniform random sampling of plans"], "C", "DP over relation subsets yields optimal bushy or left-deep orders in time exponential only in table count, practical for few-way joins."],
  ["Query Optimization", "Hard", "Histogram statistics maintained by the optimizer primarily improve:", ["Disk rotational speed", "Cardinality and selectivity estimates for skewed data distributions", "Network latency between client and server", "Transaction log size"], "B", "Even value-distribution summaries correct the uniformity assumption, preventing grossly wrong row-count estimates."],
  ["Query Optimization", "Hard", "Decorrelation is the rewrite that converts a correlated subquery into:", ["A recursive CTE in all cases", "A stored procedure call", "A view definition", "An equivalent join executed set-at-a-time, which is frequently far cheaper"], "D", "Removing per-row evaluation unlocks standard join algorithms and better plan enumeration."],

  ["File and Storage Systems", "Easy", "The fundamental unit of data transfer between disk and memory in a DBMS is the:", ["Byte", "Block (page)", "Tuple", "Field"], "B", "The buffer pool moves fixed-size pages, and all tuple storage is organized within them."],
  ["File and Storage Systems", "Easy", "A heap file organizes records by:", ["Sorting them on a key", "Hash-partitioning them", "Placing records in arbitrary order, making appends cheap but searches require a full scan", "Marking the file read-only"], "C", "Heap files offer fast insertion but no ordering benefit for retrieval."],
  ["File and Storage Systems", "Easy", "RAID level 1 provides reliability through:", ["Mirroring, keeping identical copies of data on pairs of drives", "Striping with parity", "Data compression", "Hot spare disks only"], "A", "Mirrored pairs tolerate a single drive failure with full duplicate data."],

  ["File and Storage Systems", "Medium", "RAID 5 is characterized by:", ["Pure striping with no fault tolerance", "Mirroring without striping", "A dedicated single parity disk", "Striping with parity distributed across all disks, tolerating one failure with usable capacity of n-1 drives"], "D", "Rotating parity removes the dedicated-parity bottleneck while surviving any single disk loss."],
  ["File and Storage Systems", "Medium", "Random disk reads are much slower than sequential reads mainly because:", ["Of CPU cache misses only", "Mechanical seek time plus rotational latency dominates each access", "The OS scheduler throttles them", "Data travels over the network"], "B", "Positioning the head dominates small random I/O, while sequential transfers amortize positioning over many blocks."],
  ["File and Storage Systems", "Medium", "Slotted-page organization is used to:", ["Support only fixed-length records", "Encrypt records transparently", "Support variable-length records via a slot directory plus compacted free space, where slots point to records that may relocate within the page", "Store tuples across multiple pages"], "C", "Slot indirection lets the page compact records without invalidating external references."],
  ["File and Storage Systems", "Medium", "In the buffer pool, a PINNED page is one that:", ["Is evicted first under LRU", "Is compressed in memory", "Is split into fragments", "Is marked un-evictable while in use, preventing it from being written back mid-access"], "D", "Pinning guarantees stability of pages a process is actively reading or modifying."],

  ["File and Storage Systems", "Hard", "Log-structured merge (LSM) tree storage engines:", ["Optimize purely for random reads", "Buffer writes in a memtable, flush immutable sorted runs, and compact them in the background, favoring write-heavy workloads at the cost of some read amplification", "Keep all rows permanently unsorted", "Eliminate the need for write-ahead logging"], "B", "Sequential flushes and background compaction turn random writes into sequential I/O, while reads may consult multiple levels aided by bloom filters."],
  ["File and Storage Systems", "Hard", "RAID 6 improves upon RAID 5 by:", ["Using no parity at all", "Mirroring every stripe", "Striping without parity", "Employing dual distributed parity, tolerating TWO simultaneous disk failures"], "D", "The second parity stripe protects against a second failure occurring during rebuild, important for large drives."],
  ["File and Storage Systems", "Hard", "Using unspanned organization with 512-byte blocks and 60-byte records, how many records fit per block and how much space is wasted?", ["9 records, 0 bytes wasted", "8 records, 40 bytes wasted", "8 records, 32 bytes wasted (8 * 60 = 480 of 512 bytes used)", "7 records, 92 bytes wasted"], "C", "Records cannot span blocks, so floor(512/60) = 8 records fit, leaving 32 unused trailing bytes."]
];

seedCourse('DBMS', Q);
