const { seedCourse } = require('./seed-helpers');

const Q = [
  // SELECT Queries
  ['SELECT Queries', 'Easy', 'Which statement retrieves all columns from the employees table?', ['SELECT * FROM employees;', 'GET * FROM employees;', 'SHOW ALL FROM employees;', 'FETCH * OF employees;'], 'A', 'The asterisk (*) after SELECT returns every column, and FROM specifies the source table.'],
  ['SELECT Queries', 'Easy', 'Which clause filters individual rows before any grouping occurs?', ['HAVING', 'WHERE', 'GROUP BY', 'ORDER BY'], 'B', 'WHERE filters raw rows before grouping; HAVING filters aggregated groups afterward.'],
  ['SELECT Queries', 'Easy', 'What does the DISTINCT keyword do in a SELECT statement?', ['Sorts the result alphabetically', 'Removes duplicate rows from the result', 'Selects a single random row', 'Returns only unique columns'], 'B', 'DISTINCT eliminates duplicate rows so each returned combination of column values appears only once.'],
  ['SELECT Queries', 'Medium', 'Which condition finds last names that begin with S?', ["WHERE last_name LIKE 'S%'", "WHERE last_name LIKE '%S'", "WHERE last_name = 'S*'", "WHERE last_name MATCHES 'S_'"], 'A', 'In LIKE patterns % matches any sequence of characters, so S% matches strings beginning with S.'],
  ['SELECT Queries', 'Medium', 'What is the default sort direction when ORDER BY salary is used?', ['DESC', 'Random order', 'ASC', 'Insertion order'], 'C', 'ORDER BY sorts ascending by default; DESC must be stated explicitly for descending order.'],
  ['SELECT Queries', 'Medium', 'Which operator tests whether a value lies within an inclusive range?', ['IN', 'EXISTS', 'BETWEEN', 'INTERSECT'], 'C', 'BETWEEN x AND y is inclusive of both endpoints and equals value >= x AND value <= y.'],
  ['SELECT Queries', 'Medium', 'How should a query find rows where the commission column has no value?', ['WHERE commission = NULL', 'WHERE commission IS NULL', 'WHERE commission == NULL', 'WHERE commission EMPTY'], 'B', 'Comparing with = NULL yields unknown, so the IS NULL predicate must be used.'],
  ['SELECT Queries', 'Hard', 'In PostgreSQL, what does SELECT DISTINCT ON (department) name, salary FROM employees ORDER BY department, salary DESC return?', ['The top-paid employee for each department', 'An error, because DISTINCT ON is invalid syntax', 'Only departments with a single employee', 'All employees ordered by department'], 'A', 'DISTINCT ON keeps the first row for each distinct value of the listed expressions based on the ORDER BY.'],
  ['SELECT Queries', 'Hard', 'In the logical processing order of a SELECT query, which clause is evaluated first?', ['SELECT', 'ORDER BY', 'FROM', 'HAVING'], 'C', 'Conceptually FROM runs first, followed by WHERE, GROUP BY, HAVING, SELECT, and finally ORDER BY.'],
  ['SELECT Queries', 'Hard', 'What does a CASE expression return when no WHEN branch matches and no ELSE is supplied?', ['0', 'NULL', 'It raises an error', 'An empty string'], 'B', 'CASE without ELSE implicitly behaves as ELSE NULL when no condition matches.'],

  // JOINs
  ['JOINs', 'Easy', 'Which join returns only the rows that have matching values in both tables?', ['LEFT OUTER JOIN', 'INNER JOIN', 'FULL OUTER JOIN', 'CROSS JOIN'], 'B', 'INNER JOIN keeps only row pairs satisfying the join condition, discarding non-matching rows from both sides.'],
  ['JOINs', 'Easy', 'Which join preserves every row of the first table even when the second table has no match?', ['LEFT JOIN', 'INNER JOIN', 'RIGHT JOIN', 'CROSS JOIN'], 'A', 'LEFT JOIN returns all left-side rows, filling missing right-side columns with NULL.'],
  ['JOINs', 'Easy', 'What does a FULL OUTER JOIN return?', ['Only rows present in both tables', 'All rows from both tables, with NULLs wherever a side lacks a match', 'Only the unmatched rows', 'Every possible pairing of rows'], 'B', 'FULL OUTER JOIN combines the behavior of LEFT and RIGHT joins, keeping unmatched rows from either side.'],
  ['JOINs', 'Medium', 'What does CROSS JOIN produce?', ['Only rows with equal join keys', 'The Cartesian product, pairing every row of one table with every row of the other', 'A single combined summary row', 'Rows matched by the USING clause'], 'B', 'CROSS JOIN has no ON condition, so an m-row table joined to an n-row table yields m*n rows.'],
  ['JOINs', 'Medium', 'The employees table stores manager_id pointing to employees.id. Showing each employee beside their manager requires which technique?', ['SELF JOIN', 'CROSS JOIN', 'UNION', 'PIVOT'], 'A', 'A self join uses two aliases of the same table so its rows can be matched to other rows of that table.'],
  ['JOINs', 'Medium', 'How does NATURAL JOIN determine which columns to match?', ['It joins automatically on every pair of columns sharing the same name', 'It requires an explicit USING clause', 'It creates a Cartesian product', 'It matches only primary keys'], 'A', 'NATURAL JOIN implicitly equates all identically named columns of the two tables.'],
  ['JOINs', 'Medium', 'Given SELECT d.name, COUNT(e.id) FROM departments d LEFT JOIN employees e ON e.dept_id = d.id GROUP BY d.name, what count appears for a department with no employees?', ['0', '1', 'NULL', 'The query fails'], 'A', 'Unmatched departments contribute one row whose e.id is NULL, which COUNT(e.id) ignores, giving 0.'],
  ['JOINs', 'Hard', 'orders has 1000 rows and duplicated customer records make every order match exactly 2 rows of customers. How many rows does the INNER JOIN return?', ['1000', '2000', '500', '1010'], 'B', 'Each order row joins against two matching customer rows, doubling the output to 2000.'],
  ['JOINs', 'Hard', 'Filtering the right table with WHERE b.flag = true versus adding AND b.flag = true to the ON clause of a LEFT JOIN differs how?', ['No difference, both behave identically', 'ON keeps all left rows with NULL right columns; WHERE discards left rows lacking a match', 'WHERE is faster in all cases', 'ON cannot reference the right table'], 'B', 'Conditions in ON only affect which right rows match, while WHERE applies after the join and can turn the LEFT JOIN into an effective INNER JOIN.'],
  ['JOINs', 'Hard', 'What capability does the LATERAL keyword add to a join in PostgreSQL?', ['The right-hand subquery may reference columns of each left-hand row', 'It forces a nested-loop execution plan', 'It disables index usage', 'It is identical to CROSS JOIN'], 'A', 'LATERAL lets the right side act like a correlated subquery evaluated per left row, enabling things like top-N-per-group joins.'],

  // Subqueries
  ['Subqueries', 'Easy', 'What must a scalar subquery return?', ['Exactly one row with one column', 'Any number of rows', 'Exactly two columns', 'A Boolean value'], 'A', 'A scalar subquery yields a single value, so it must return one row and one column.'],
  ['Subqueries', 'Easy', 'Which operator tests whether a subquery returns at least one row?', ['ANY', 'EXISTS', 'LIKE', 'UNIQUE'], 'B', 'EXISTS evaluates to true when the subquery produces at least one row and stops scanning immediately.'],
  ['Subqueries', 'Easy', 'What does WHERE dept_id IN (SELECT id FROM departments) accomplish?', ['Matches rows whose dept_id equals any id returned by the subquery', 'Requires the subquery to return exactly one row', 'Joins the tables physically', 'Deletes non-matching rows'], 'A', 'IN checks membership against every value produced by the subquery.'],
  ['Subqueries', 'Medium', 'What characterizes a correlated subquery?', ['It references columns from the outer query and is logically evaluated once per outer row', 'It always executes only one time', 'It cannot appear in WHERE', 'It must be wrapped in a CTE'], 'A', 'Because it depends on outer-query values, a correlated subquery is re-evaluated for each candidate row.'],
  ['Subqueries', 'Medium', 'What does WHERE salary > ALL (SELECT salary FROM managers) mean?', ['Salary exceeds every value returned, i.e. more than the maximum', 'Salary exceeds at least one returned value', 'Salary equals the average', 'The comparison ignores NULLs automatically'], 'A', '> ALL demands the value compare greater than each result, making it equivalent to exceeding the maximum.'],
  ['Subqueries', 'Medium', 'Why can NOT IN return no rows when the subquery result contains a NULL?', ['x NOT IN (list with NULL) evaluates to unknown for every row', 'NULLs are treated as zeros', 'The database converts NOT IN to an outer join', 'NOT IN ignores NULL values silently'], 'A', 'Comparing anything with NULL yields unknown, so no row can satisfy the NOT IN condition.'],
  ['Subqueries', 'Medium', 'What is required for a subquery used as a derived table in the FROM clause?', ['It must be given a correlation alias', 'It must contain a GROUP BY', 'It can return multiple identical column names freely', 'It must use EXISTS'], 'A', 'Every table expression in FROM needs a name, so the derived table must be aliased.'],
  ['Subqueries', 'Hard', 'Which rewrite typically performs best for attaching per-customer order totals to every customer row?', ['Join customers to a grouped derived table: JOIN (SELECT cust_id, SUM(amount) s FROM orders GROUP BY cust_id) t ON t.cust_id = c.id', 'Use a correlated scalar subquery summing orders for each customer', 'Loop over customers with a cursor', 'Concatenate order amounts into a string per customer'], 'A', 'Aggregating once in a derived table then joining avoids recomputing the aggregate per outer row.'],
  ['Subqueries', 'Hard', 'What advantage does a CTE introduced with WITH provide over repeating the same subquery several times?', ['The logic is written and named once and can be referenced multiple times, improving clarity and maintenance', 'It always executes faster than any subquery', 'It bypasses transaction logging', 'It locks the referenced tables exclusively'], 'A', 'A CTE factors a query into a named temporary result that later query parts can reuse by name.'],
  ['Subqueries', 'Hard', 'In SELECT c.name, (SELECT COUNT(*) FROM orders o WHERE o.cust_id = c.id) AS cnt FROM customers c, what does cnt show for a customer with zero orders?', ['0, because COUNT over an empty set is 0', 'NULL, because the subquery finds nothing', 'The query errors out', 'The total across all customers'], 'A', 'COUNT(*) always returns a number, returning 0 when the correlated subquery matches no rows.'],

  // Indexing
  ['Indexing', 'Easy', 'What is the main purpose of an index?', ['Speed up data retrieval at some cost to writes and storage', 'Encrypt sensitive columns', 'Guarantee referential integrity', 'Compress table storage'], 'A', 'Indexes provide fast lookup structures, trading extra disk space and slower writes for quicker queries.'],
  ['Indexing', 'Easy', 'Which statement builds an index on the last_name column of employees?', ['CREATE INDEX idx_emp_last ON employees (last_name);', 'ADD INDEX TO employees(last_name);', 'MAKE INDEX idx_emp_last IN employees;', 'INDEX TABLE employees SET last_name;'], 'A', 'CREATE INDEX name ON table (column) is the standard syntax.'],
  ['Indexing', 'Easy', 'What defines a composite index?', ['A single index built over multiple columns', 'Two indexes on the same column', 'An index maintained in another database', 'An index created during backup'], 'A', 'A composite (multi-column) index orders entries by a tuple of columns rather than one column.'],
  ['Indexing', 'Medium', 'What distinguishes a clustered index?', ['It dictates the physical storage order of table rows and only one can exist per table', 'It stores rows in a separate hash table', 'Multiple clustered indexes may exist per table', 'It never affects range scan speed'], 'A', 'Because leaf pages hold the actual rows in key order, a table can have just one clustered index.'],
  ['Indexing', 'Medium', 'When is an index called a covering index for a query?', ['The index holds every column the query needs, avoiding access to the base table', 'It covers all rows of every table', 'It encrypts the queried data', 'It was created by the database installer'], 'A', 'If requested columns live in the index itself, the engine skips costly heap fetches, often marked as index-only scans.'],
  ['Indexing', 'Medium', 'Creating a UNIQUE index on email has which combined effect?', ['Enforces uniqueness of emails and accelerates equality lookups', 'Allows duplicates but speeds searches', 'Prevents NULL entries in all cases', 'Automatically clusters the table'], 'A', 'Unique indexes serve both as a constraint mechanism and as a regular search structure.'],
  ['Indexing', 'Medium', 'Why can WHERE name LIKE "%son" fail to use a B-tree index on name?', ['A leading wildcard leaves no known prefix for the tree to seek', 'LIKE is never index-supported', 'Text columns cannot be indexed', 'The optimizer dislikes lowercase patterns'], 'A', 'B-tree seeks rely on a known starting prefix; a leading % forces a full scan of index or table.'],
  ['Indexing', 'Hard', 'What lookup complexity does a balanced B-tree index provide for equality searches?', ['O(log n)', 'O(n)', 'O(n log n)', 'O(1) always'], 'A', 'Descending a height-balanced B-tree touches a logarithmic number of pages relative to entry count.'],
  ['Indexing', 'Hard', 'With composite index (last_name, first_name, hire_date), which predicate can seek directly using the index?', ['last_name = X AND first_name = Y', 'first_name = Y alone', 'hire_date = Z alone', 'first_name = Y AND hire_date = Z'], 'A', 'The leftmost-prefix rule lets the index serve predicates starting from its first column(s) contiguously.'],
  ['Indexing', 'Hard', 'What does CREATE INDEX idx_active ON orders (created_at) WHERE status = "active" create?', ['A partial index covering only rows with status active', 'A full index refreshed hourly', 'An index on the status column only', 'A materialized statistic'], 'A', 'A partial index stores entries solely for rows meeting the predicate, shrinking size and maintenance cost.'],

  // Normalization
  ['Normalization', 'Easy', 'What is the primary goal of normalization?', ['Reduce redundancy and update anomalies by organizing attributes into well-structured tables', 'Make queries run slower but safer', 'Combine all data into one wide table', 'Encrypt data at rest'], 'A', 'Normalized schemas store each fact once, preventing insertion, update, and deletion anomalies.'],
  ['Normalization', 'Easy', 'What does First Normal Form (1NF) require?', ['Atomic column values with no repeating groups', 'No transitive dependencies', 'Every determinant being a candidate key', 'Separate tables for each relationship'], 'A', '1NF forbids arrays or repeated column groups inside a single cell.'],
  ['Normalization', 'Easy', 'Second Normal Form (2NF) builds on 1NF by removing what?', ['Partial dependencies of non-key columns on part of a composite primary key', 'All foreign keys', 'Duplicate indexes', 'Calculated columns'], 'A', 'In 2NF every non-key attribute depends on the whole composite key, not merely a portion of it.'],
  ['Normalization', 'Medium', 'Third Normal Form (3NF) specifically eliminates which kind of dependency?', ['Transitive dependencies where non-key columns depend on other non-key columns', 'Multivalued dependencies', 'Dependencies of key attributes on themselves', 'Join dependencies'], 'A', '3NF requires non-key attributes to depend only on the key, removing chains such as key to A to B.'],
  ['Normalization', 'Medium', 'What condition defines Boyce-Codd Normal Form (BCNF)?', ['Every determinant in the relation is a candidate key', 'All attributes are prime', 'The relation has exactly one foreign key', 'Each table stores at most two columns'], 'A', 'BCNF tightens 3NF so nothing except candidate keys may determine other attributes.'],
  ['Normalization', 'Medium', 'Why might a team deliberately denormalize a reporting schema?', ['Fewer joins and precomputed values improve read performance despite added redundancy', 'To increase update anomaly protection', 'To satisfy 5NF', 'To shrink storage consumption'], 'A', 'Denormalization trades write consistency risk for faster reads by duplicating or aggregating data.'],
  ['Normalization', 'Medium', 'In a customers table keyed by customer_id, city is determined by zip_code, and zip_code is determined by customer_id. Which normal form does this violate?', ['3NF, due to a transitive dependency', '1NF, because city is text', 'BCNF only if the table has two rows', 'No normal form is violated'], 'A', 'City depends on the key through the non-key zip_code, creating a forbidden transitive chain.'],
  ['Normalization', 'Hard', 'Fourth Normal Form (4NF) addresses which situation?', ['Independent multivalued facts stored together, producing unnecessary row combinations', 'Floating-point rounding in numeric keys', 'Missing foreign key indexes', 'Case-insensitive text comparisons'], 'A', '4NF forbids nontrivial multivalued dependencies unless the determinant is a candidate key.'],
  ['Normalization', 'Hard', 'Relation R(A,B,C) has functional dependencies A to B and B to C, with A the only candidate key. What is the highest normal form R satisfies?', ['2NF', '3NF', 'BCNF', '4NF'], 'A', 'The single-attribute key rules out partial dependencies, but C depends transitively through B, violating 3NF while leaving 2NF intact.'],
  ['Normalization', 'Hard', 'A decomposition is lossless-join when which property holds?', ['Joining the projected tables restores exactly the original rows with no spurious tuples', 'Both projections share at most one column', 'Each projection is in BCNF automatically', 'The join executes in logarithmic time'], 'A', 'Lossless decomposition guarantees the original relation can always be reconstructed precisely.'],

  // Aggregate Functions
  ['Aggregate Functions', 'Easy', 'How does AVG(salary) treat NULL salaries?', ['They are ignored in both sum and count', 'They count as zero', 'They force the result to NULL whenever any exists', 'They raise an error'], 'A', 'Aggregate functions skip NULL inputs, averaging only the populated values.'],
  ['Aggregate Functions', 'Easy', 'Which function returns the largest value in a column?', ['MAX', 'TOP', 'GREATEST_SET', 'CEILING'], 'A', 'MAX scans the group and returns its greatest input, working on numbers, strings, and dates alike.'],
  ['Aggregate Functions', 'Easy', 'Why is HAVING required rather than WHERE to filter on COUNT(*)?', ['WHERE runs before grouping, so aggregates do not exist yet', 'WHERE cannot reference numeric columns', 'HAVING is simply faster', 'COUNT is illegal in SELECT lists'], 'A', 'Group aggregation happens after row filtering, so post-aggregation conditions belong in HAVING.'],
  ['Aggregate Functions', 'Medium', 'What distinguishes COUNT(phone) from COUNT(*)?', ['COUNT(phone) counts only rows where phone is not NULL, while COUNT(*) counts all rows', 'They always return identical values', 'COUNT(phone) counts distinct values by default', 'COUNT(*) ignores rows with any NULL'], 'A', 'Passing a column makes COUNT skip its NULLs; the star form tallies every row regardless.'],
  ['Aggregate Functions', 'Medium', 'With GROUP BY department, city, how many groups form?', ['One per unique department-and-city pair', 'One per department only', 'One per city only', 'Exactly two groups overall'], 'A', 'Multi-column GROUP BY treats the combination of listed values as the grouping key.'],
  ['Aggregate Functions', 'Medium', 'What does SUM(bonus) return for a group where bonus is NULL in every row?', ['NULL', '0', 'An error', 'Negative infinity'], 'A', 'Summing no non-NULL inputs yields NULL, so reports often wrap it as COALESCE(SUM(bonus), 0).'],
  ['Aggregate Functions', 'Medium', 'Applying MIN(hire_date) to a DATE column yields what?', ['The earliest hire date in the group', 'An error because MIN needs numbers', 'The latest date reversed', 'The count of dates'], 'A', 'MIN and MAX operate on any orderable type including temporal and character types.'],
  ['Aggregate Functions', 'Hard', 'What does COUNT(DISTINCT city) compute?', ['The number of different non-NULL cities in the group', 'Total rows including duplicates', 'Cities appearing exactly once', 'NULL when duplicates exist'], 'A', 'DISTINCT deduplicates inputs first, and remaining NULLs are still excluded by COUNT.'],
  ['Aggregate Functions', 'Hard', 'Which expression portably counts high-value orders inside one grouped query across major databases?', ['SUM(CASE WHEN amount > 1000 THEN 1 ELSE 0 END)', 'COUNT(amount > 1000)', 'TOTAL IF amount > 1000', 'COUNT HIGH amount'], 'A', 'CASE turns a condition into ones summed by SUM, a pattern supported wherever CASE exists.'],
  ['Aggregate Functions', 'Hard', 'What does GROUP BY GROUPING SETS ((region), (product), ()) produce?', ['Three result sets: totals by region, by product, and one grand-total row', 'Only the grand total', 'A cross tab of region by product cells only', 'An error in standard SQL'], 'A', 'GROUPING SETS computes each specified aggregation level within a single pass of the grouped query.'],

  // Views
  ['Views', 'Easy', 'What is a view in a relational database?', ['A stored named query that behaves like a virtual table', 'A physical copy of a table kept in sync nightly', 'A special index on multiple tables', 'A database role with limited rights'], 'A', 'A view holds no data itself; querying it runs its defining SELECT against base tables.'],
  ['Views', 'Easy', 'Which command removes a view named v_sales?', ['DROP VIEW v_sales;', 'DELETE VIEW v_sales;', 'REMOVE v_sales;', 'TRUNCATE VIEW v_sales;'], 'A', 'DROP VIEW deletes the view definition without touching underlying table data.'],
  ['Views', 'Easy', 'Which benefit do views directly provide?', ['Hiding selected columns or rows from users for simpler, safer access', 'Guaranteed faster execution than the equivalent query', 'Automatic backups of base tables', 'Compression of stored rows'], 'A', 'Views abstract complexity and can expose only permitted subsets of data to specific roles.'],
  ['Views', 'Medium', 'How does a materialized view differ from a regular view?', ['It physically stores the query result and reflects changes only after a refresh', 'It cannot contain joins', 'It disappears after each session ends', 'It is limited to one table'], 'A', 'Materialized views persist computed results, trading freshness for read speed until refreshed.'],
  ['Views', 'Medium', 'Which feature generally makes a simple single-table view updatable?', ['A one-to-one mapping between view rows and base-table rows without GROUP BY, DISTINCT, or aggregation', 'Adding an ORDER BY to the view', 'Declaring the view WITH NO DATA', 'Naming the view with a v_ prefix'], 'A', 'When each view row corresponds to exactly one base row, the engine can route INSERT, UPDATE, and DELETE through it.'],
  ['Views', 'Medium', 'What does WITH CHECK OPTION enforce on an updatable view?', ['INSERT or UPDATE statements cannot create rows that the view WHERE clause would exclude', 'Queries against the view are cached', 'The view refreshes on every read', 'Base tables become read-only'], 'A', 'CHECK OPTION rejects modifications whose resulting rows would fall outside the visible view predicate.'],
  ['Views', 'Medium', 'What does CREATE OR REPLACE VIEW achieve?', ['Redefines an existing view while preserving its granted permissions', 'Duplicates the view under a new name', 'Converts a view into a materialized view', 'Drops all dependent objects silently'], 'A', 'OR REPLACE swaps the definition in place, keeping privileges and dependent references intact.'],
  ['Views', 'Hard', 'In PostgreSQL, what is required for REFRESH MATERIALIZED VIEW CONCURRENTLY to succeed?', ['The materialized view must have a UNIQUE index matching its rows', 'The view must be defined WITH NO DATA', 'All users must disconnect during refresh', 'The underlying tables must be empty'], 'A', 'The unique index lets concurrent readers keep querying old contents while differences are applied.'],
  ['Views', 'Hard', 'Why does wrapping a slow query in a plain view rarely improve its performance by itself?', ['The optimizer expands the view into the outer query and optimizes the whole statement as one', 'Views compile to stored procedures with caching', 'View definitions force serial execution', 'Views add mandatory encryption overhead'], 'A', 'Non-materialized views add naming convenience only; execution cost stays that of the underlying query.'],
  ['Views', 'Hard', 'Why is a view built on a multi-table JOIN with GROUP BY normally not updatable?', ['Result rows no longer correspond uniquely to a single base-table row that a change could target', 'Joins disable the transaction log', 'GROUP BY views are dropped nightly', 'Updatability requires at least three tables'], 'A', 'Ambiguous mapping from aggregate or joined output back to one source row prevents safe UPDATE routing.'],

  // Transactions
  ['Transactions', 'Easy', 'What do the letters of ACID stand for?', ['Atomicity, Consistency, Isolation, Durability', 'Access, Control, Integrity, Data', 'Atomic, Concurrent, Indexed, Distributed', 'Availability, Consistency, Idempotency, Durability'], 'A', 'These four properties define reliable transactional behavior in database systems.'],
  ['Transactions', 'Easy', 'What effect does ROLLBACK have on the current transaction?', ['Undoes all changes made since the transaction began', 'Makes all changes permanent', 'Commits only the last statement', 'Locks the affected tables'], 'A', 'ROLLBACK reverses the transaction, restoring data to its state before BEGIN.'],
  ['Transactions', 'Easy', 'Which command starts an explicit transaction?', ['BEGIN TRANSACTION', 'OPEN TRANSACTION', 'START TX BLOCK', 'INIT WORK'], 'A', 'BEGIN TRANSACTION (or START TRANSACTION) opens a unit of work ended by COMMIT or ROLLBACK.'],
  ['Transactions', 'Medium', 'What is a dirty read?', ['Reading data another transaction has changed but not yet committed', 'Reading the same row twice with different values', 'Reading phantom rows inserted by a committed transaction', 'Reading from a standby replica'], 'A', 'Dirty reads expose uncommitted state that the writer may later roll back.'],
  ['Transactions', 'Medium', 'What is the default isolation level in PostgreSQL?', ['READ COMMITTED', 'READ UNCOMMITTED', 'REPEATABLE READ', 'SERIALIZABLE'], 'A', 'Each statement in READ COMMITTED sees a fresh snapshot of already-committed data.'],
  ['Transactions', 'Medium', 'After SAVEPOINT s1 inside a transaction, what does ROLLBACK TO SAVEPOINT s1 do?', ['Undoes work performed after s1 while keeping the surrounding transaction and earlier work alive', 'Rolls back the entire transaction', 'Commits everything up to s1', 'Deletes the savepoint and continues unchanged'], 'A', 'Savepoints enable partial undo without abandoning the whole transaction.'],
  ['Transactions', 'Medium', 'Which isolation level provides the strictest correctness guarantee?', ['SERIALIZABLE', 'READ COMMITTED', 'REPEATABLE READ', 'SNAPSHOT DIRTY'], 'A', 'SERIALIZABLE ensures concurrent transactions produce a result equivalent to some sequential order.'],
  ['Transactions', 'Hard', 'How do modern databases typically resolve a deadlock between two transactions?', ['Detect the lock cycle and abort one victim transaction so the other proceeds, letting applications retry', 'Grant both transactions unlimited locks', 'Silently merge the two transactions', 'Disable locking until the system restarts'], 'A', 'Cycle detection chooses a victim whose rollback breaks the wait-for graph, returning an error clients can retry.'],
  ['Transactions', 'Hard', 'Under the standard SQL definitions, which anomaly does REPEATABLE READ prevent that READ COMMITTED permits?', ['Non-repeatable reads, where rereading a row shows changed values', 'Lost updates on absent rows', 'Reading committed data', 'Durability failures after commit'], 'A', 'REPEATABLE READ pins row versions for the transaction, while READ COMMITTED may see newer commits between statements.'],
  ['Transactions', 'Hard', 'What benefit does Multi-Version Concurrency Control (MVCC) provide?', ['Readers consult snapshots and never block writers, and vice versa', 'All transactions execute strictly one at a time', 'Locks are eliminated from the engine entirely', 'Writes bypass the WAL for speed'], 'A', 'MVCC keeps multiple row versions so consistent reads proceed without blocking concurrent modifications.'],

  // Constraints
  ['Constraints', 'Easy', 'What dual guarantee does a PRIMARY KEY provide?', ['Values are unique and cannot be NULL', 'Values are encrypted and indexed remotely', 'Values auto-increment and expire', 'Values are unique per session only'], 'A', 'A primary key identifies each row, so the engine enforces both uniqueness and non-nullness.'],
  ['Constraints', 'Easy', 'What does a FOREIGN KEY constraint maintain?', ['Referential integrity between child values and parent table keys', 'Uniqueness across unrelated tables', 'Encrypted links between databases', 'Automatic index creation on every column'], 'A', 'Foreign keys reject child rows whose referencing value has no matching parent key.'],
  ['Constraints', 'Easy', 'What does declaring a column NOT NULL ensure?', ['Every inserted or updated row must supply a value for it', 'The column gets a unique index', 'The column becomes the primary key', 'Empty strings are rejected too'], 'A', 'NOT NULL blocks NULL assignments while still permitting empty strings or zeroes if typed so.'],
  ['Constraints', 'Medium', 'Which constraint rejects rows failing an arbitrary boolean rule such as price >= 0?', ['CHECK', 'ASSERT ROW', 'VALIDATE', 'TRIGGER ONLY'], 'A', 'CHECK evaluates a predicate on insert or update and aborts violating statements.'],
  ['Constraints', 'Medium', 'In PostgreSQL, how many NULL values may a UNIQUE column hold?', ['Multiple, since NULL is not equal to any value including another NULL', 'At most one', 'None whatsoever', 'Exactly two'], 'A', 'Uniqueness compares values, and NULL never equals NULL, so distinct NULL rows coexist.'],
  ['Constraints', 'Medium', 'What happens to child rows when a parent row is deleted under ON DELETE CASCADE?', ['They are deleted automatically', 'They become orphaned silently', 'The delete is refused', 'Their foreign keys switch to the root row'], 'A', 'CASCADE propagates the deletion down to referencing rows in child tables.'],
  ['Constraints', 'Medium', 'When does a DEFAULT clause take effect?', ['When an INSERT omits the column, the declared default value is stored', 'On every UPDATE regardless of supplied values', 'Only during table creation', 'Whenever the column value is NULL'], 'A', 'DEFAULT fills omitted columns at insert time; explicit NULLs still require nullable columns.'],
  ['Constraints', 'Hard', 'What does INITIALLY DEFERRED on a constraint mean?', ['Its check runs at COMMIT, allowing intermediate statements to violate it temporarily', 'It is ignored until someone VALIDATEs it manually', 'It applies only to deferred triggers', 'It checks before each statement instead'], 'A', 'Deferrable constraints postpone verification to commit time, easing multi-row reorderings such as swapping unique keys.'],
  ['Constraints', 'Hard', 'What is the purpose of a PostgreSQL EXCLUDE constraint?', ['Reject rows where a chosen operator over listed columns is true, such as date ranges overlapping via &&', 'Exclude the table from backups', 'Block all foreign keys on the table', 'Skip NULL rows during indexing'], 'A', 'Backed by GiST indexes, EXCLUDE generalizes uniqueness to conditions like non-overlapping scheduling periods.'],
  ['Constraints', 'Hard', 'Why add a heavy CHECK or FK with NOT VALID and later run VALIDATE CONSTRAINT?', ['Enforcement begins immediately for new writes while validation scans existing rows under only a brief lock', 'It converts the constraint to deferrable automatically', 'It skips validating existing data forever', 'It disables the constraint for sessions'], 'A', 'This split lets production traffic continue mostly unblocked while historical rows are verified asynchronously.'],

  // String & Date Functions
  ['String & Date Functions', 'Easy', "What does LOWER('SQL Course') return?", ['sql course', 'SQL COURSE', 'Sql Course', 'sqlcourse'], 'A', 'LOWER converts every alphabetic character to lowercase, leaving others untouched.'],
  ['String & Date Functions', 'Easy', 'What does LENGTH(first_name) return in PostgreSQL?', ['The number of characters in the value', 'The bytes of the entire row', 'The count of words', 'The column width limit'], 'A', 'LENGTH measures characters of the given string argument.'],
  ['String & Date Functions', 'Easy', 'What does CURRENT_DATE return?', ["Today's date with no time component", "Today's date and current time", 'The server startup date', 'The timezone offset'], 'A', 'CURRENT_DATE is a date-typed value holding only year, month, and day.'],
  ['String & Date Functions', 'Medium', 'What does CONCAT(first_name, " ", last_name) evaluate to for Ada and Lovelace?', ['Ada Lovelace', 'AdaLovelace', 'Ada , Lovelace', 'Lovelace Ada'], 'A', 'CONCAT glues its arguments together exactly, honoring the embedded space.'],
  ['String & Date Functions', 'Medium', 'What does SUBSTRING("Database", 1, 4) return?', ['Data', 'taba', 'base', 'Datab'], 'A', 'Starting at position 1 and taking 4 characters yields Data.'],
  ['String & Date Functions', 'Medium', "What does TRIM('  hello  ') return?", ['hello', 'hello  ', '  hello', 'hello middle spaces removed everywhere'], 'A', 'TRIM strips leading and trailing spaces by default, preserving interior characters.'],
  ['String & Date Functions', 'Medium', "What does EXTRACT(MONTH FROM DATE '2024-07-15') return?", ['7', 'July', '15', '2024'], 'A', 'EXTRACT pulls the requested datetime field as a numeric value, here the month 7.'],
  ['String & Date Functions', 'Hard', 'How do REPLACE and TRANSLATE differ?', ['REPLACE substitutes whole substrings, while TRANSLATE swaps characters position-by-position', 'They are synonyms in every database', 'TRANSLATE only uppercases text', 'REPLACE works solely on dates'], 'A', 'REPLACE searches for a full search string, whereas TRANSLATE maps individual source characters to targets.'],
  ['String & Date Functions', 'Hard', "What does date_trunc('month', TIMESTAMP '2024-07-15 10:30:45') return?", ['2024-07-01 00:00:00', '2024-07-31 23:59:59', '2024-07-15 00:00:00', '2024-01-01 00:00:00'], 'A', 'date_trunc resets all fields finer than month, landing on the first instant of July.'],
  ['String & Date Functions', 'Hard', "In PostgreSQL, what type does TIMESTAMP '2024-01-10' - TIMESTAMP '2023-12-31' yield?", ['An interval representing the elapsed days and time', 'An integer day count', 'A timestamp at epoch', 'It raises a type error'], 'A', 'Timestamp subtraction produces an interval capturing the exact elapsed duration.']
];

seedCourse('SQL', Q);
